// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from server/internal/protocol. DO NOT EDIT.
// Regenerate with `make protocol`.

//////////
// source: protocol.go
/*
Package protocol is the single source of truth for the wire between the Go
server and the TypeScript client. Every exported type and constant here is
mirrored into client/src/protocol.gen.ts by tygo (`make protocol`); the
generated file must never be edited by hand.
*/

/**
 * TurnSeconds is the full world-turn period out of combat. Lowered 5→4
 * (playtest feedback batch 3, item 1; playtest 2026-07-11: a 3 s input
 * window felt slow) — the plan's §9 "feel-test the cadence" decision
 * landing at 2 s input / 2 s playback.
 */
export const TurnSeconds = 4;
/**
 * InputWindowSeconds is the slice of the turn in which intents are accepted.
 * Lowered 3→2 alongside TurnSeconds (see above).
 */
export const InputWindowSeconds = 2;
/**
 * PlaybackSeconds is the client-side animation window after resolution.
 */
export const PlaybackSeconds = 2;
/**
 * CombatRadius is the mutual-line-of-sight distance (in hexes) at which a
 * combat time bubble forms around a player and a hostile.
 */
export const CombatRadius = 6;
/**
 * MonsterAggroRadius is the hex distance at which a WORLD-domain monster
 * notices a player and starts hunting it; beyond it, a monster stands
 * still (#36 — no wander this slice). It MUST stay strictly greater than
 * CombatRadius: a monster has to notice a player before it can close the
 * distance into a combat bubble, or it would sit frozen just outside
 * aggro range forever. A monster already inside a combat bubble ignores
 * this and keeps chasing its bubble's players unconditionally — a fight
 * is a fight.
 */
export const MonsterAggroRadius = 10;
/**
 * MonsterLeashMultiplier sizes a WORLD-domain monster's default leash
 * radius (#102): a monster farther than MonsterLeashMultiplier × its own
 * base aggro radius from its home (spawn) hex drops any chase and walks
 * back home, ignoring players until it arrives. A monster kind can
 * override the derived radius directly (monsterDef.leashRadius), the same
 * way it overrides aggroRadius. Monsters inside a combat bubble ignore
 * the leash entirely — a fight is a fight.
 */
export const MonsterLeashMultiplier = 2;
/**
 * StackCap is the maximum number of friendly entities on one hex — sized
 * so a full party fits.
 */
export const StackCap = 5;
/**
 * RepathDetourSlack bounds how far out of its way a PLAYER's queued walk
 * will go around something standing in it (#96): when the next step is
 * blocked, the re-routed path is taken only if it is at most this many
 * hexes longer than the route it replaces — otherwise the walker waits
 * where it is, path retained, exactly as it did before #96.
 * The guard exists because blockers are TRANSIENT: the monster in your way
 * has usually moved on by next turn. Rounding a single blocker on open hex
 * terrain costs about +2, a full StackCap blob about +4; a detour that
 * costs more than that means a real chokepoint, where standing still for a
 * turn beats hiking around the map.
 */
export const RepathDetourSlack = 4;
/**
 * RingCount is the number of distance-based difficulty rings worldgen
 * bands the map into (milestone 6c): ring 0 (home) through RingCount-1
 * (frontier). Monster-kind registry validation requires every ring to
 * have at least one kind that spawns in it.
 */
export const RingCount = 3;
/**
 * SanctuaryRadius is the hex distance from the origin within which no
 * hostile monster spawns (milestone 6c) — the seed of a future trade
 * hub (plan §9 recovery entry). Deliberately smaller than CombatRadius:
 * the player-proximity spawn guard (#36) already keeps a fresh spawn
 * clear of an instant fight, so the sanctuary's job is the PERMANENT
 * safe zone, not spawn-moment safety.
 */
export const SanctuaryRadius = 5;
/**
 * DragonCount is the maximum number of dragons SpawnMonsters places in
 * one world — the rare, ring-2 boss kind.
 */
export const DragonCount = 1;
/**
 * MaxChatLen caps a chat message length in runes (defence-in-depth; the
 * client also caps input). MaxNameLen caps a player's display name.
 */
export const MaxChatLen = 500;
/**
 * World rules that both sides need to agree on.
 */
export const MaxNameLen = 24;
/**
 * SystemSender is the reserved chat-sender label the server uses for its own
 * announcements (party ops etc.). The client styles any message from this
 * sender as a server line, so a player may not take it as a name (#198).
 * Shared here so the reserved-name check and the label cannot drift apart.
 */
export const SystemSender = "system";
/**
 * Hex is an axial coordinate on the flat-top hex grid. See Red Blob Games'
 * hex guide for the coordinate math conventions.
 */
export interface Hex {
  q: number /* int */;
  r: number /* int */;
}
/**
 * Terrain is a tile's ground type. Wire values are strings for a readable
 * stream; the set is closed — the client renders unknown terrain as rock.
 */
export type Terrain = string;
/**
 * The terrain set. Rock is impassable and rings the world edge; water is
 * impassable but open; grass and forest are walkable.
 */
export const TerrainGrass: Terrain = "grass";
/**
 * The terrain set. Rock is impassable and rings the world edge; water is
 * impassable but open; grass and forest are walkable.
 */
export const TerrainForest: Terrain = "forest";
/**
 * The terrain set. Rock is impassable and rings the world edge; water is
 * impassable but open; grass and forest are walkable.
 */
export const TerrainWater: Terrain = "water";
/**
 * The terrain set. Rock is impassable and rings the world edge; water is
 * impassable but open; grass and forest are walkable.
 */
export const TerrainRock: Terrain = "rock";
/**
 * Entity kinds. Players join; monsters are spawned hostiles. The set is closed;
 * a client renders an unknown kind as a monster (safer than as a player).
 */
export const EntityPlayer = "player";
/**
 * Entity kinds. Players join; monsters are spawned hostiles. The set is closed;
 * a client renders an unknown kind as a monster (safer than as a player).
 */
export const EntityMonster = "monster";
/**
 * Classes: the three playable character types.
 */
export const ClassFighter = "fighter";
/**
 * Classes: the three playable character types.
 */
export const ClassRogue = "rogue";
/**
 * Classes: the three playable character types.
 */
export const ClassMage = "mage";
/**
 * Species: the three player species with distinct passive bonuses.
 */
export const SpeciesHuman = "human";
/**
 * Species: the three player species with distinct passive bonuses.
 */
export const SpeciesElf = "elf";
/**
 * Species: the three player species with distinct passive bonuses.
 */
export const SpeciesDwarf = "dwarf";
/**
 * Intent kinds: the type of an IntentRequest. Kind is required — it must be
 * one of the constants below. Every inventory action (equip, unequip, drop,
 * pickup, drink) follows one shared rule: outside a combat bubble it applies
 * immediately and costs nothing; inside a bubble it is the player's
 * committed action for that turn.
 */
export const IntentMove = "move";
/**
 * Intent kinds: the type of an IntentRequest. Kind is required — it must be
 * one of the constants below. Every inventory action (equip, unequip, drop,
 * pickup, drink) follows one shared rule: outside a combat bubble it applies
 * immediately and costs nothing; inside a bubble it is the player's
 * committed action for that turn.
 */
export const IntentAttack = "attack";
/**
 * IntentEquip equips an owned item (IntentRequest.ItemID) from the
 * backpack into its type-derived slot, swapping any displaced occupant
 * back into the vacated backpack entry. Naming an already-equipped item
 * toggles it OFF (equivalent to IntentUnequip — playtest batch 2's
 * toggle behavior, kept).
 */
export const IntentEquip = "equip";
/**
 * IntentUnequip moves an equipped item (IntentRequest.ItemID) back into a
 * free backpack entry; rejected if the backpack is full.
 */
export const IntentUnequip = "unequip";
/**
 * IntentDrop drops an owned item (IntentRequest.ItemID) — equipped or in
 * the backpack; a consumable stack drops whole — onto the player's own
 * hex as ground item(s).
 */
export const IntentDrop = "drop";
/**
 * IntentPickup picks up one ground item (IntentRequest.GroundItemID) from
 * the player's own hex: merged into a matching consumable stack first,
 * else into a free backpack entry; rejected with a clear error if
 * neither exists. Items never auto-equip on pickup. Replaces walk-over
 * auto-pickup (the inventory-slots milestone).
 */
export const IntentPickup = "pickup";
/**
 * IntentLearnSkill spends a banked skill point on a learnable skill
 * (IntentRequest.SkillID) — #124. Unlike every other inventory-ish
 * action this is NOT queueable inside a combat bubble: learning is a
 * between-fights decision, so it is rejected outright in combat rather
 * than costing a bubble turn.
 */
export const IntentLearnSkill = "learn-skill";
/**
 * IntentDrink drinks one unit of an owned consumable stack
 * (IntentRequest.ItemID): applies the def's heal (clamped to max HP) and
 * decrements the stack; an emptied stack frees its backpack entry.
 */
export const IntentDrink = "drink";
/**
 * IntentUseSkill triggers a learned ACTIVE skill (IntentRequest.SkillID)
 * at IntentRequest.Target — #161. It is the turn's action, exactly like a
 * move: it does not stack with one, and it is not a bonus action.
 */
export const IntentUseSkill = "use-skill";
/**
 * The item taxonomy (gear keystone, #55/#56): one weapon type carrying
 * tags, plus armor/jewelry types that each map 1:1 to an equip slot.
 */
export const ItemTypeWeapon = "weapon";
/**
 * The item taxonomy (gear keystone, #55/#56): one weapon type carrying
 * tags, plus armor/jewelry types that each map 1:1 to an equip slot.
 */
export const ItemTypeConsumable = "consumable";
/**
 * The item taxonomy (gear keystone, #55/#56): one weapon type carrying
 * tags, plus armor/jewelry types that each map 1:1 to an equip slot.
 */
export const ItemTypeHelmet = "helmet";
/**
 * The item taxonomy (gear keystone, #55/#56): one weapon type carrying
 * tags, plus armor/jewelry types that each map 1:1 to an equip slot.
 */
export const ItemTypeChest = "chest";
/**
 * The item taxonomy (gear keystone, #55/#56): one weapon type carrying
 * tags, plus armor/jewelry types that each map 1:1 to an equip slot.
 */
export const ItemTypeGloves = "gloves";
/**
 * The item taxonomy (gear keystone, #55/#56): one weapon type carrying
 * tags, plus armor/jewelry types that each map 1:1 to an equip slot.
 */
export const ItemTypeBoots = "boots";
/**
 * The item taxonomy (gear keystone, #55/#56): one weapon type carrying
 * tags, plus armor/jewelry types that each map 1:1 to an equip slot.
 */
export const ItemTypeRing = "ring";
/**
 * The item taxonomy (gear keystone, #55/#56): one weapon type carrying
 * tags, plus armor/jewelry types that each map 1:1 to an equip slot.
 */
export const ItemTypeAmulet = "amulet";
/**
 * ItemTypeShield occupies the off-hand — pure defence, never fires as a
 * hit (#90, S4 of #55).
 */
export const ItemTypeShield = "shield";
/**
 * Weapon tags: which attacks fire the weapon (§3 of the keystone spec).
 */
export const WeaponTagMelee = "melee";
/**
 * Weapon tags: which attacks fire the weapon (§3 of the keystone spec).
 */
export const WeaponTagRanged = "ranged";
/**
 * Weapon tags: which attacks fire the weapon (§3 of the keystone spec).
 */
export const WeaponTagMagic = "magic";
/**
 * ForestSightCost is what one forest hex between two entities costs a line of
 * sight, in hexes of effective range (#95). Rock blocks sight outright;
 * forest SOFTENS it — you see a long way over open grass and only a short way
 * into trees. Against CombatRadius that reads: 6 hexes over grass, ~4 through
 * one belt of trees, ~2 through two.
 */
export const ForestSightCost = 2;
/**
 * Damage types (#92, DT1): every attack carries exactly one, and resistances
 * and vulnerabilities are take-damage rule cards conditioned on it — one
 * vocabulary shared by the engine, content, and the client tooltip. Three
 * families of two: physical (Sharp/Blunt), elemental (Fire/Ice), and
 * metaphysical (Holy/Chaos).
 * The families and the Holy↔Chaos / Fire↔Ice oppositions are an AUTHORING
 * CONVENTION, not machinery: all six types are mechanically flat, and a
 * "Chaos monster fears Holy" is a vulnerability card someone wrote, not an
 * axis the engine knows about. Promotable to a real axis later if content
 * always ends up mirrored.
 */
export const DamageTypeSharp = "sharp";
/**
 * Damage types (#92, DT1): every attack carries exactly one, and resistances
 * and vulnerabilities are take-damage rule cards conditioned on it — one
 * vocabulary shared by the engine, content, and the client tooltip. Three
 * families of two: physical (Sharp/Blunt), elemental (Fire/Ice), and
 * metaphysical (Holy/Chaos).
 * The families and the Holy↔Chaos / Fire↔Ice oppositions are an AUTHORING
 * CONVENTION, not machinery: all six types are mechanically flat, and a
 * "Chaos monster fears Holy" is a vulnerability card someone wrote, not an
 * axis the engine knows about. Promotable to a real axis later if content
 * always ends up mirrored.
 */
export const DamageTypeBlunt = "blunt";
/**
 * Damage types (#92, DT1): every attack carries exactly one, and resistances
 * and vulnerabilities are take-damage rule cards conditioned on it — one
 * vocabulary shared by the engine, content, and the client tooltip. Three
 * families of two: physical (Sharp/Blunt), elemental (Fire/Ice), and
 * metaphysical (Holy/Chaos).
 * The families and the Holy↔Chaos / Fire↔Ice oppositions are an AUTHORING
 * CONVENTION, not machinery: all six types are mechanically flat, and a
 * "Chaos monster fears Holy" is a vulnerability card someone wrote, not an
 * axis the engine knows about. Promotable to a real axis later if content
 * always ends up mirrored.
 */
export const DamageTypeFire = "fire";
/**
 * Damage types (#92, DT1): every attack carries exactly one, and resistances
 * and vulnerabilities are take-damage rule cards conditioned on it — one
 * vocabulary shared by the engine, content, and the client tooltip. Three
 * families of two: physical (Sharp/Blunt), elemental (Fire/Ice), and
 * metaphysical (Holy/Chaos).
 * The families and the Holy↔Chaos / Fire↔Ice oppositions are an AUTHORING
 * CONVENTION, not machinery: all six types are mechanically flat, and a
 * "Chaos monster fears Holy" is a vulnerability card someone wrote, not an
 * axis the engine knows about. Promotable to a real axis later if content
 * always ends up mirrored.
 */
export const DamageTypeIce = "ice";
/**
 * Damage types (#92, DT1): every attack carries exactly one, and resistances
 * and vulnerabilities are take-damage rule cards conditioned on it — one
 * vocabulary shared by the engine, content, and the client tooltip. Three
 * families of two: physical (Sharp/Blunt), elemental (Fire/Ice), and
 * metaphysical (Holy/Chaos).
 * The families and the Holy↔Chaos / Fire↔Ice oppositions are an AUTHORING
 * CONVENTION, not machinery: all six types are mechanically flat, and a
 * "Chaos monster fears Holy" is a vulnerability card someone wrote, not an
 * axis the engine knows about. Promotable to a real axis later if content
 * always ends up mirrored.
 */
export const DamageTypeHoly = "holy";
/**
 * Damage types (#92, DT1): every attack carries exactly one, and resistances
 * and vulnerabilities are take-damage rule cards conditioned on it — one
 * vocabulary shared by the engine, content, and the client tooltip. Three
 * families of two: physical (Sharp/Blunt), elemental (Fire/Ice), and
 * metaphysical (Holy/Chaos).
 * The families and the Holy↔Chaos / Fire↔Ice oppositions are an AUTHORING
 * CONVENTION, not machinery: all six types are mechanically flat, and a
 * "Chaos monster fears Holy" is a vulnerability card someone wrote, not an
 * axis the engine knows about. Promotable to a real axis later if content
 * always ends up mirrored.
 */
export const DamageTypeChaos = "chaos";
/**
 * Equip-slot names. Armor slots equal their item type; weapons go to a
 * hand (main first, then off; two-handed locks both).
 */
export const SlotMainHand = "main-hand";
/**
 * Equip-slot names. Armor slots equal their item type; weapons go to a
 * hand (main first, then off; two-handed locks both).
 */
export const SlotOffHand = "off-hand";
/**
 * Equip-slot names. Armor slots equal their item type; weapons go to a
 * hand (main first, then off; two-handed locks both).
 */
export const SlotHelmet = ItemTypeHelmet;
/**
 * Equip-slot names. Armor slots equal their item type; weapons go to a
 * hand (main first, then off; two-handed locks both).
 */
export const SlotChest = ItemTypeChest;
/**
 * Equip-slot names. Armor slots equal their item type; weapons go to a
 * hand (main first, then off; two-handed locks both).
 */
export const SlotGloves = ItemTypeGloves;
/**
 * Equip-slot names. Armor slots equal their item type; weapons go to a
 * hand (main first, then off; two-handed locks both).
 */
export const SlotBoots = ItemTypeBoots;
/**
 * Equip-slot names. Armor slots equal their item type; weapons go to a
 * hand (main first, then off; two-handed locks both).
 */
export const SlotRing = ItemTypeRing;
/**
 * Equip-slot names. Armor slots equal their item type; weapons go to a
 * hand (main first, then off; two-handed locks both).
 */
export const SlotAmulet = ItemTypeAmulet;
/**
 * BackpackSize is the fixed number of backpack entries every entity has (the
 * inventory-slots milestone). An entry holds one gear instance, or one
 * consumable stack (identical defs merge up to ItemStackCap; stacks never
 * split).
 */
export const BackpackSize = 4;
/**
 * ItemStackCap is the maximum count of identical consumables in one backpack
 * stack. Distinct from StackCap (max FRIENDLY ENTITIES on one hex) — same
 * launch value, unrelated invariant, kept as separate named constants so a
 * future tuning change to one never accidentally reads as the other.
 */
export const ItemStackCap = 5;
/**
 * Starting/maximum hit points by kind. HP is on the wire from milestone 6.2 so
 * the client can show health bars once combat (6.3) starts changing it.
 * MonsterMaxHP is superseded by per-kind maxHP (internal/game's monsterDef
 * registry, milestone 6c) — wolf's entry carries this exact value forward —
 * but stays here as the historical baseline several tests still pin against.
 */
export const PlayerMaxHP = 20;
/**
 * Starting/maximum hit points by kind. HP is on the wire from milestone 6.2 so
 * the client can show health bars once combat (6.3) starts changing it.
 * MonsterMaxHP is superseded by per-kind maxHP (internal/game's monsterDef
 * registry, milestone 6c) — wolf's entry carries this exact value forward —
 * but stays here as the historical baseline several tests still pin against.
 */
export const MonsterMaxHP = 10;
/**
 * RegenPerTurn is the HP a player passively recovers each WORLD-domain turn
 * resolution while out of combat (bubbleID == 0) and below max HP — the
 * passive recovery layer (plan §9). It kills the inverted incentive where
 * dying (a full-HP respawn) was the only way to heal: standing around out of
 * a fight now tops you up too, slowly. Monsters never regen; a bubbled player
 * (mid-fight) does not either — being in a fight means no regen.
 */
export const RegenPerTurn = 1;
/**
 * XPCurveBase scales the quadratic XP curve: the total XP required to
 * REACH level L is XPCurveBase * (L-1)^2 (#60, roadmap XP1). Gaps grow
 * linearly: 100, 300, 500, ...
 */
export const XPCurveBase = 100;
/**
 * QuestKillRewardPerTarget is the flat per-target XP a kill quest's
 * reward is built from (targetN * QuestKillRewardPerTarget), independent
 * of which monster kind actually gets killed toward it — deliberately
 * decoupled from monsterDef.xp (a kind's own combat kill award) since
 * 6c introduced per-kind XP.
 */
export const QuestKillRewardPerTarget = 20;
/**
 * FighterMaxHP is the level-1 max HP for Fighter class (tanky melee).
 */
export const FighterMaxHP = 30;
/**
 * RogueMaxHP is the level-1 max HP for Rogue class (high single-target damage, squishy).
 */
export const RogueMaxHP = 16;
/**
 * MageMaxHP is the level-1 max HP for Mage class (AoE ranged, squishy).
 */
export const MageMaxHP = 14;
/**
 * FistsDamage is level-1 damage for fallback/unarmed attacks (the empty
 * close-slot fallback; see internal/game's fistsDef).
 */
export const FistsDamage = 1;
/**
 * HPGainBase/HPGainMin shape the front-loaded HP curve (#60, roadmap
 * XP2): the max-HP gain when advancing FROM level n is
 * max(HPGainMin, HPGainBase-(n-1)) — 8,7,6,...,1 then +1 forever.
 */
export const HPGainBase = 8;
/**
 * Per-class base stats (level 1). Level scaling: MaxHP += the front-loaded
 * curve's cumulative bonus (see HPGainBase/HPGainMin below).
 * Weapon damage/range/AoE are content data now (internal/game's item
 * registry, milestone 6b.4) — see itemDamage there; levels do not scale
 * damage (#60, roadmap XP3: no raw-stat scaling — levels give HP and,
 * later, skill points).
 */
export const HPGainMin = 1;
/**
 * ElfCritChancePercent is the percent base crit chance for Elf species.
 */
export const ElfCritChancePercent = 20;
/**
 * ElfCritMultiplier is the damage multiplier for Elf crits.
 */
export const ElfCritMultiplier = 2;
/**
 * DwarfDamageReduction is the flat damage reduction per attack for Dwarf species.
 */
export const DwarfDamageReduction = 1;
/**
 * SkillPointsPerLevel is the skill-point bank grant every player earns per
 * level gained (#124). Raised 2 -> 3 alongside SkillPointCost 1 -> 3
 * (#57/#161 tuning, 2026-07-19): at 2/level a 3-point cost would have made
 * the Human +1 worth a third of a skill every level instead of a rounding
 * difference, so raising both keeps the species gap where it was.
 */
export const SkillPointsPerLevel = 3;
/**
 * SkillPointCost is what learning ONE skill costs from the bank —
 * uniform across passives and actives (maintainer's call, 2026-07-19).
 */
export const SkillPointCost = 3;
/**
 * HumanBonusSkillPoints is the EXTRA point a Human earns per level — the
 * species perk that replaces the XP multiplier (#123/#124 task 8). Not a
 * rule card: a per-level bank grant is not a fold over a combat value.
 */
export const HumanBonusSkillPoints = 1;
/**
 * RogueGlanceChancePercent is the percent chance an incoming hit on a
 * Rogue only glances (GlanceDamagePercent applies).
 */
export const RogueGlanceChancePercent = 20;
/**
 * GlanceDamagePercent is a glancing hit's damage multiplier in percent
 * (50 = half damage), shared by any future glance-granting content.
 */
export const GlanceDamagePercent = 50;
/**
 * Tile is one hex of the world map.
 */
export interface Tile {
  hex: Hex;
  terrain: Terrain;
}
/**
 * MapResponse is the payload of GET /api/map: the full static world map.
 * Fetched once at client startup; entities move in turn bundles, the ground
 * does not, so the map is not part of the SSE stream.
 */
export interface MapResponse {
  /**
   * Radius is the map's hex radius: every tile satisfies
   * distance(origin, hex) <= Radius.
   */
  radius: number /* int */;
  tiles: Tile[];
}
/**
 * EventTurn announces a resolved world turn. Its SSE id is the turn
 * number so EventSource reconnection can resume via Last-Event-ID.
 */
export const EventTurn = "turn";
/**
 * EventHeartbeat is a keep-alive frame. It carries no id (it is not a turn
 * and must not advance Last-Event-ID) and fires on a fixed HeartbeatInterval
 * so the client's liveness watchdog stays fed even when a frozen combat
 * clock stops turn frames.
 */
export const EventHeartbeat = "heartbeat";
/**
 * EventChat announces a chat message. It carries NO id (chat is not a turn
 * and must not advance Last-Event-ID); its data is a JSON ChatMessage.
 */
export const EventChat = "chat";
/**
 * BubbleView is a window into a combat bubble: who's in it, which members it's
 * still waiting on, and how long until the patience timeout. Every bundle
 * carries all active bubbles; a client picks the one whose MemberIDs include
 * its own entity to drive its combat HUD.
 */
export interface BubbleView {
  id: number /* int64 */;
  memberIds: number /* int64 */[];
  waitingForIds: number /* int64 */[];
  patienceRemainingMs: number /* int64 */;
}
/**
 * TurnEvent is the payload of an EventTurn frame: the world state after a
 * resolved turn. A full entity snapshot every turn keeps clients trivially
 * resyncable at this player count; deltas are a later optimization if ever
 * needed. It will grow (attacks, deaths, chat) as the game develops.
 */
export interface TurnEvent {
  /**
   * Turn is a monotonically increasing resolution counter, incremented on
   * every world-domain tick AND every combat-bubble resolution (they advance
   * on independent clocks). Monotonic, so it still serves as the SSE id /
   * Last-Event-ID watermark; it is not a pure world-turn count.
   */
  turn: number /* int64 */;
  /**
   * IntervalMs is the runtime turn period in milliseconds (the configured
   * TURN_INTERVAL). The client cannot derive this — TURN_INTERVAL is
   * env-configurable while the cadence constants are fixed — so it rides
   * each bundle and the client re-syncs its playback/input phase clock on
   * every arrival.
   */
  intervalMs: number /* int64 */;
  /**
   * Entities is every entity in the world, sorted by ID.
   */
  entities: Entity[];
  /**
   * Bubbles is every active combat time bubble in the world; a client filters
   * to the one containing its own entity.
   */
  bubbles: BubbleView[];
  /**
   * Quests is the whole quest board, sorted by ID.
   */
  quests: QuestView[];
  /**
   * GroundItems is every dropped item currently lying on the map.
   */
  groundItems: GroundItemView[];
  /**
   * Hits is every hit landed in the last few turn resolutions (see
   * HitView's doc for the coalescing/dedupe contract) — the per-hit
   * crit/glance moments the HP deltas alone can't express (#114).
   */
  hits: HitView[];
  /**
   * WorldID identifies this running world instance — a random hex string
   * minted once at world creation and persisted in the snapshot (so a
   * restored world is still considered the SAME world). It never changes
   * while the process/snapshot lineage is unbroken, and rides every turn
   * bundle so a client can tell a genuine world reset (a restart with no
   * matching snapshot, or a fresh world under a different snapshot lineage)
   * from an ordinary reconnect: if a bundle's WorldID differs from the
   * first one this client ever saw, the world underneath it changed (item
   * 4, playtest feedback batch 3).
   */
  worldId: string;
}
/**
 * HitView is one landed hit from a recent turn resolution, riding the turn
 * bundle so the client can render per-hit combat moments (#114) — most
 * importantly whether the hit was a crit (an attacker-side chance-conditioned
 * damage multiplier fired: elf passive, Misericorde, Duelist's Saber) or a
 * glance (a defender-side chance-conditioned reduction fired: the Rogue
 * passive — a halved hit, never a miss; see docs/game-identity.md for why the
 * vocabulary is crit/glance, never miss/dodge). Purely cosmetic: Amount is
 * the same damage already reflected in the entities' HP — the client must
 * never apply it again.
 * Turn is the resolution that produced the hit. The server keeps hits from
 * the last few resolutions in every bundle (SSE ticks coalesce — a slow
 * client skips intermediate bundles), so a client renders only hits with
 * Turn greater than the last bundle it processed and ignores the rest.
 */
export interface HitView {
  turn: number /* int64 */;
  attackerId: number /* int64 */;
  victimId: number /* int64 */;
  amount: number /* int */;
  crit: boolean;
  glance: boolean;
}
/**
 * QuestState is a quest's lifecycle stage on the board.
 */
export type QuestState = string;
/**
 * The quest lifecycle. Completed quests stay completed — the board depletes
 * (repeatable quests arrive with continuous monster spawning, later).
 */
export const QuestAvailable: QuestState = "available";
/**
 * The quest lifecycle. Completed quests stay completed — the board depletes
 * (repeatable quests arrive with continuous monster spawning, later).
 */
export const QuestTaken: QuestState = "taken";
/**
 * The quest lifecycle. Completed quests stay completed — the board depletes
 * (repeatable quests arrive with continuous monster spawning, later).
 */
export const QuestCompleted: QuestState = "completed";
/**
 * QuestView is one quest on the board as the client sees it. The whole board
 * (~6 rows) rides every turn bundle (full-snapshot philosophy); the client
 * picks out its own quest by holder id.
 */
export interface QuestView {
  id: number /* int64 */;
  name: string;
  /**
   * Kind is "kill" (slay TargetN monsters) or "reach" (stand on GoalHex).
   */
  kind: string;
  targetN: number /* int */;
  goalHex: Hex;
  progress: number /* int */;
  rewardXp: number /* int */;
  state: QuestState;
  /**
   * The holder when taken: at most one of these is non-zero.
   */
  holderEntityId: number /* int64 */;
  holderPartyId: number /* int64 */;
}
/**
 * SkillView is one skill as the wire shows it (#124) — NEAR-SIGHTED by
 * construction: the server sends only skills the viewer has LEARNED or can
 * learn right now, so a locked skill never reaches the client and the tree
 * cannot leak even by accident.
 */
export interface SkillView {
  id: string;
  name: string;
  /**
   * Tree is one of the three tree names ("class"/"adventure"/"survival").
   */
  tree: string;
  /**
   * Stats are the rendered stat lines (#171); Flavor is the authored lore
   * line. Mechanical text is never authored beside a card.
   */
  stats: StatView[];
  flavor: string;
  /**
   * Learned distinguishes an owned skill from one currently learnable.
   */
  learned: boolean;
}
/**
 * StatView is one rendered stat line (#171) — "+50% Chaos Resistance",
 * "×2 Damage vs Adjacent". Derived server-side from the item's rule cards, so
 * the text and the mechanic can never disagree; the client only draws it.
 */
export interface StatView {
  text: string;
  /**
   * Drawback marks a stat that makes its holder WORSE (Iron Plate Armor's
   * +25% Aggro Range), so the client can style it apart. Sign alone cannot
   * say: +25% Aggro Range is bad, +5% XP is good.
   */
  drawback: boolean;
}
/**
 * ItemView is one owned item as the client sees it: display stats plus
 * whether it currently sits in its slot. The numbers ride the wire so the
 * client never compiles against item content.
 */
export interface ItemView {
  id: number /* int64 */;
  defId: string;
  name: string;
  /**
   * Type is the item's itemType (the ItemType* consts above) — the equip
   * slot this item occupies or would occupy (hand name for weapons; the
   * slot key equals the type for armor/jewelry; consumables have no slot).
   */
  type: string;
  /**
   * Tags names which attacks fire a weapon (WeaponTagMelee/Ranged/Magic);
   * empty for a non-weapon item.
   */
  tags: string[];
  /**
   * DamageType is the DamageType* a weapon deals (#92) — what resistances
   * and vulnerabilities key on; empty for a non-weapon item.
   */
  damageType: string;
  /**
   * TwoHanded is true for a weapon that occupies main-hand AND locks
   * off-hand; always false for a non-weapon item.
   */
  twoHanded: boolean;
  damage: number /* int */;
  rangeHex: number /* int */;
  aoeRadius: number /* int */;
  /**
   * Stats are the rendered stat lines (#171), in display order.
   */
  stats: StatView[];
  /**
   * Flavor is the item's authored lore ("Fantasy") line; empty for items
   * without lore. Cosmetic only — flavor text in the inventory tooltip.
   */
  flavor: string;
  equipped: boolean;
  /**
   * Count is the stack size for a consumable backpack stack (1..ItemStackCap);
   * always 1 for gear.
   */
  count: number /* int */;
}
/**
 * GroundItemView is one dropped stack lying on the map, waiting to be picked
 * up (IntentPickup). ID is the representative item instance id (stable client
 * key, and the id a pickup intent names). Type feeds the client's pickup
 * prompt (name + type); Count is the stack size (a consumable stack drops
 * whole — 1..ItemStackCap; always 1 for gear). The detail fields mirror
 * ItemView so the pickup modal can show what an item IS before you take it
 * (#139) — same meanings as on ItemView.
 */
export interface GroundItemView {
  id: number /* int64 */;
  hex: Hex;
  defId: string;
  name: string;
  type: string;
  count: number /* int */;
  /**
   * Detail fields (#139) — identical meanings to ItemView's.
   */
  tags: string[];
  damageType: string;
  twoHanded: boolean;
  damage: number /* int */;
  rangeHex: number /* int */;
  aoeRadius: number /* int */;
  desc: string;
  stats: StatView[];
  flavor: string;
}
/**
 * Entity is one thing standing on the map: a player or a monster.
 */
export interface Entity {
  id: number /* int64 */;
  hex: Hex;
  kind: string;
  class: string;
  species: string;
  hp: number /* int */;
  maxHp: number /* int */;
  inCombat: boolean;
  /**
   * Reach is a MONSTER's attack range in hexes (0 = melee) — the one threat
   * stat shown to a player before contact (#201). Its damage and damage type
   * are deliberately NOT sent: those are learned by being hit (near-sighted
   * combat). Players send 0 (their own reach is their equipped weapon's,
   * already known to them).
   */
  reach: number /* int */;
  /**
   * XP is server-authoritative; monsters send 0, players send their actual XP.
   */
  xp: number /* int */;
  /**
   * Level is server-authoritative; monsters send 1, players send their actual level.
   */
  level: number /* int */;
  /**
   * Name is the entity's display name: the player's chosen name for a
   * player, or the monster kind's display name ("Wolf", "Dragon", ...)
   * for a monster (milestone 6c — previously always empty for monsters).
   */
  name: string;
  /**
   * PartyID groups players into a party (≥2 members share a non-zero id);
   * 0 means solo. Monsters are always 0. The roster and on-map partymate
   * coloring are derived client-side by grouping entities on this.
   */
  partyId: number /* int64 */;
  /**
   * Items is the entity's owned items. Players only; monsters send none.
   */
  items: ItemView[];
  /**
   * Skills is the viewer's OWN learned + currently-learnable skills (#124);
   * empty on every other entity, since skills are own-only on the wire.
   */
  skills: SkillView[];
  /**
   * SkillPoints is the viewer's own unspent bank; zero on other entities.
   */
  skillPoints: number /* int */;
  /**
   * MonsterKind is the monster-kind registry id ("wolf", "dragon", ...);
   * empty for players. Drives per-kind client rendering (color/glyph).
   */
  monsterKind: string;
}
/**
 * JoinRequest is the body of POST /api/join. A returning client sends its
 * stored token to reclaim its entity; an empty token means "new player".
 */
export interface JoinRequest {
  token: string;
  /**
   * Name is the player's display name (chat sender label). Required for a
   * new player (non-empty after trim, at most MaxNameLen runes); ignored on
   * a reclaim (known token) — an existing entity already has its name.
   */
  name: string;
  /**
   * Class is the player's chosen class. Required for a new player (empty
   * token or unknown token): must be ClassFighter, ClassRogue, or
   * ClassMage. Ignored on a reclaim (known token) — an existing entity
   * already has its class.
   */
  class: string;
  /**
   * Species is the player's chosen species. Required for a new player (empty
   * token or unknown token): must be SpeciesHuman, SpeciesElf, or
   * SpeciesDwarf. Ignored on a reclaim (known token) — an existing entity
   * already has its species.
   */
  species: string;
}
/**
 * JoinResponse identifies the caller's entity. The token is the bearer
 * secret for submitting intents — the "name + secret link" auth of the plan,
 * minus the name for now.
 */
export interface JoinResponse {
  entityId: number /* int64 */;
  token: string;
  hex: Hex;
}
/**
 * IntentRequest is the body of POST /api/intent: "walk to Target" or "attack Target".
 * Target is any walkable hex (for move) or target hex (for attack), not just a
 * neighbor — the server pathfinds from the entity's current position and walks the
 * route one hex per turn. A keyboard step is simply a Target one hex away. One
 * intent per entity per turn; a later submission in the same input window replaces
 * the earlier intent.
 */
export interface IntentRequest {
  entityId: number /* int64 */;
  token: string;
  /**
   * Kind is the intent type. Required: one of the Intent* constants (move,
   * attack, equip, unequip, drop, pickup, drink).
   */
  kind: string;
  target: Hex;
  /**
   * ItemID names the OWNED item an inventory action targets. Equip,
   * unequip, drop, and drink intents only.
   */
  itemId: number /* int64 */;
  /**
   * SkillID names the skill a learn-skill intent spends a point on (#124).
   */
  skillId: string;
  /**
   * GroundItemID names the GROUND item a pickup targets (GroundItemView.ID;
   * it must lie on the player's own hex). Pickup intents only.
   */
  groundItemId: number /* int64 */;
  /**
   * TargetEntityID names a single-target ranged attack's victim by entity
   * id instead of a hex (item 7, playtest batch 2): 0 = none (ground-
   * targeted — a mage's AoE cast, whose blast radius makes a hex the
   * natural target). A bow-class attack (aoeRadius 0) sets this instead of
   * relying on Target; the server resolves against the named entity's
   * pre-move hex (#104), so a committed shot tracks a sidestepping or
   * fleeing target by id rather than a stale hex. Attack intents only.
   */
  targetEntityId: number /* int64 */;
}
/**
 * ChatMessage is the payload of an EventChat frame: one line in the global
 * channel. Seq is a server-assigned monotonic sequence (a stable client key
 * and ordering aid — not a timestamp). Sender is the author's display name.
 */
export interface ChatMessage {
  seq: number /* int64 */;
  sender: string;
  text: string;
}
/**
 * ChatRequest is the body of POST /api/chat. Token authenticates the sender;
 * Text is the message (or a "/command"). The server resolves the sender's
 * name and position from the token — the client cannot set them.
 */
export interface ChatRequest {
  token: string;
  text: string;
}
/**
 * ErrorResponse is the JSON body of every non-2xx API response.
 */
export interface ErrorResponse {
  error: string;
}
