// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from server/internal/protocol. DO NOT EDIT.
// Regenerate with `make protocol`.

//////////
// source: protocol.go
/*
Package protocol is the single source of truth for the wire between the Go
server and the TypeScript client. Every exported type and constant here is
mirrored into client/src/protocol.gen.ts by tygo (`make protocol`); the
generated file must never be edited by hand.
*/

/**
 * TurnSeconds is the full world-turn period out of combat.
 */
export const TurnSeconds = 5;
/**
 * InputWindowSeconds is the slice of the turn in which intents are accepted.
 */
export const InputWindowSeconds = 3;
/**
 * PlaybackSeconds is the client-side animation window after resolution.
 */
export const PlaybackSeconds = 2;
/**
 * CombatRadius is the mutual-line-of-sight distance (in hexes) at which a
 * combat time bubble forms around a player and a hostile.
 */
export const CombatRadius = 6;
/**
 * StackCap is the maximum number of friendly entities on one hex — sized
 * so a full party fits.
 */
export const StackCap = 5;
/**
 * Hex is an axial coordinate on the flat-top hex grid. See Red Blob Games'
 * hex guide for the coordinate math conventions.
 */
export interface Hex {
  q: number /* int */;
  r: number /* int */;
}
/**
 * Terrain is a tile's ground type. Wire values are strings for a readable
 * stream; the set is closed — the client renders unknown terrain as rock.
 */
export type Terrain = string;
/**
 * The terrain set. Rock is impassable and rings the world edge; water is
 * impassable but open; grass and forest are walkable.
 */
export const TerrainGrass: Terrain = "grass";
/**
 * The terrain set. Rock is impassable and rings the world edge; water is
 * impassable but open; grass and forest are walkable.
 */
export const TerrainForest: Terrain = "forest";
/**
 * The terrain set. Rock is impassable and rings the world edge; water is
 * impassable but open; grass and forest are walkable.
 */
export const TerrainWater: Terrain = "water";
/**
 * The terrain set. Rock is impassable and rings the world edge; water is
 * impassable but open; grass and forest are walkable.
 */
export const TerrainRock: Terrain = "rock";
/**
 * Tile is one hex of the world map.
 */
export interface Tile {
  hex: Hex;
  terrain: Terrain;
}
/**
 * MapResponse is the payload of GET /api/map: the full static world map.
 * Fetched once at client startup; entities move in turn bundles, the ground
 * does not, so the map is not part of the SSE stream.
 */
export interface MapResponse {
  /**
   * Radius is the map's hex radius: every tile satisfies
   * distance(origin, hex) <= Radius.
   */
  radius: number /* int */;
  tiles: Tile[];
}
/**
 * SSE event names on the GET /api/events stream. The stream also carries
 * comment frames as heartbeats; those have no event name and no payload.
 */
/**
 * EventTurn announces a resolved world turn. Its SSE id is the turn
 * number so EventSource reconnection can resume via Last-Event-ID.
 */
export const EventTurn = "turn";
/**
 * TurnEvent is the payload of an EventTurn frame: the world state after a
 * resolved turn. A full entity snapshot every turn keeps clients trivially
 * resyncable at this player count; deltas are a later optimization if ever
 * needed. It will grow (attacks, deaths, chat) as the game develops.
 */
export interface TurnEvent {
  /**
   * Turn is the monotonically increasing world-turn number.
   */
  turn: number /* int64 */;
  /**
   * Entities is every entity in the world, sorted by ID.
   */
  entities: Entity[];
}
/**
 * Entity is one thing standing on the map. For now every entity is a player;
 * kinds (monsters, NPCs) come with later milestones.
 */
export interface Entity {
  id: number /* int64 */;
  hex: Hex;
}
/**
 * JoinRequest is the body of POST /api/join. A returning client sends its
 * stored token to reclaim its entity; an empty token means "new player".
 */
export interface JoinRequest {
  token: string;
}
/**
 * JoinResponse identifies the caller's entity. The token is the bearer
 * secret for submitting intents — the "name + secret link" auth of the plan,
 * minus the name for now.
 */
export interface JoinResponse {
  entityId: number /* int64 */;
  token: string;
  hex: Hex;
}
/**
 * IntentRequest is the body of POST /api/intent: "on the next turn, step to
 * Target". Target must be adjacent and walkable. One intent per entity per
 * turn; a later submission in the same input window replaces the earlier one.
 */
export interface IntentRequest {
  entityId: number /* int64 */;
  token: string;
  target: Hex;
}
/**
 * ErrorResponse is the JSON body of every non-2xx API response.
 */
export interface ErrorResponse {
  error: string;
}
